### ISSUE TITLE
Missing papers

### ISSUE THREAD

**Issue by weiqinchen7** [dunnolab/awesome-in-context-rl#6]
Hi, thank you for collecting the amazing ICRL literature. I believe there are some missing ICRL papers as shown below. Thanks!

Can large language models explore in-context?

SAD: State-Action Distillation for In-Context Reinforcement Learning under Random Policies

Pretraining Decision Transformers with Reward Prediction for In-Context Multi-task Structured Bandit Learning

Transformers Learn Temporal Difference Methods for In-Context Reinforcement Learning

**Comment by vkurenkov** [comment]
Hi,

These all are very relevant papers, thanks for pointing out.

Could you create a pull request with these additions? We will merge ASAP.
